"""
design_tab_scaffold.py -- generate a settings "Design tab" proposal.

Usage:
    python design_tab_scaffold.py --framework react|vue|plain
                                  --config <design-config.json>
                                  [--out <dir>]

Caller: design-full/SKILL.md (P6 customization, design-tab track).
No existing script serves this purpose.
JSON fields emitted to stdout: out, framework, files.
Task: read design-config.json; emit embedded-template scaffold files for the
      target framework (react/vue/plain) plus always WIRING.md.
      NEVER write outside --out directory.

Constraints: Python 3 stdlib only, ASCII-only output, deterministic, silent
no-op on bad input (exits 0 with {"error": "..."}).
"""

import argparse
import json
import os
import sys


# ---------------------------------------------------------------------------
# React templates
# ---------------------------------------------------------------------------

_REACT_DESIGN_SETTINGS_TSX = '''\
// DesignSettings.tsx -- PROPOSAL (see WIRING.md before integrating)
// Generated by design_tab_scaffold.py -- ASCII-only, no decorative unicode.

import React, {{ useState }} from "react";
import {{ applyDesignConfig }} from "./applyDesignConfig";

export interface DesignConfig {{
  version: number;
  theme: {{
    modes: string[];
    default: string;
  }};
  density: {{
    options: string[];
    default: string;
  }};
  accent: {{
    options: string[];
    default: string;
  }};
  avatars: {{
    sets: string[];
    default: string;
    enabled: boolean;
  }};
  effects: Array<{{
    id: string;
    label: string;
    enabled: boolean;
    reduced_motion_behavior: string;
    fallback: string;
  }}>;
}}

interface Props {{
  config: DesignConfig;
}}

export const DesignSettings: React.FC<Props> = ({{ config }}) => {{
  const [theme, setTheme] = useState<string>(config.theme.default);
  const [density, setDensity] = useState<string>(config.density.default);
  const [accent, setAccent] = useState<string>(config.accent.default);
  const [avatarSet, setAvatarSet] = useState<string>(
    config.avatars.enabled ? config.avatars.default : ""
  );
  const [effects, setEffects] = useState<Record<string, boolean>>(
    Object.fromEntries(config.effects.map((e) => [e.id, e.enabled]))
  );

  const handleChange = (updates: Partial<{{
    theme: string;
    density: string;
    accent: string;
    avatarSet: string;
    effects: Record<string, boolean>;
  }}>) => {{
    const next = {{ theme, density, accent, avatarSet, effects, ...updates }};
    applyDesignConfig(next, config);
  }};

  return (
    <div className="design-settings" data-density={{density}}>
      <h2>Design Settings</h2>

      <section>
        <label>Theme</label>
        <select
          value={{theme}}
          onChange={{(e) => {{ setTheme(e.target.value); handleChange({{ theme: e.target.value }}); }}}}
        >
          {{config.theme.modes.map((m) => (
            <option key={{m}} value={{m}}>{{m}}</option>
          ))}}
        </select>
      </section>

      <section>
        <label>Density</label>
        <select
          value={{density}}
          onChange={{(e) => {{ setDensity(e.target.value); handleChange({{ density: e.target.value }}); }}}}
        >
          {{config.density.options.map((d) => (
            <option key={{d}} value={{d}}>{{d}}</option>
          ))}}
        </select>
      </section>

      <section>
        <label>Accent color</label>
        <div style={{{{ display: "flex", gap: "8px" }}}}>
          {{config.accent.options.map((color) => (
            <button
              key={{color}}
              style={{{{
                background: color,
                width: 32,
                height: 32,
                border: accent === color ? "3px solid #000" : "2px solid #ccc",
                borderRadius: 4,
                cursor: "pointer",
              }}}}
              aria-label={{`Select accent ${{color}}`}}
              onClick={{() => {{ setAccent(color); handleChange({{ accent: color }}); }}}}
            />
          ))}}
        </div>
      </section>

      {{config.avatars.enabled && (
        <section>
          <label>Avatar style</label>
          <select
            value={{avatarSet}}
            onChange={{(e) => {{ setAvatarSet(e.target.value); handleChange({{ avatarSet: e.target.value }}); }}}}
          >
            {{config.avatars.sets.map((s) => (
              <option key={{s}} value={{s}}>{{s}}</option>
            ))}}
          </select>
        </section>
      )}}

      {{config.effects.length > 0 && (
        <section>
          <label>Effects</label>
          {{config.effects.map((effect) => (
            <label key={{effect.id}} style={{{{ display: "flex", alignItems: "center", gap: 8 }}}}>
              <input
                type="checkbox"
                checked={{effects[effect.id] ?? effect.enabled}}
                onChange={{(e) => {{
                  const next = {{ ...effects, [effect.id]: e.target.checked }};
                  setEffects(next);
                  handleChange({{ effects: next }});
                }}}}
              />
              {{effect.label}}
              {{effect.fallback ? ` (fallback: ${{effect.fallback}})` : ""}}
            </label>
          ))}}
        </section>
      )}}
    </div>
  );
}};

export default DesignSettings;
'''

_REACT_APPLY_CONFIG_TS = '''\
// applyDesignConfig.ts -- PROPOSAL (see WIRING.md before integrating)
// Generated by design_tab_scaffold.py -- ASCII-only output.

export interface AppliedSettings {{
  theme: string;
  density: string;
  accent: string;
  avatarSet: string;
  effects: Record<string, boolean>;
}}

interface EffectDef {{
  id: string;
  reduced_motion_behavior: string;
}}

interface Config {{
  effects: EffectDef[];
}}

export function applyDesignConfig(settings: AppliedSettings, config: Config): void {{
  const root = document.documentElement;

  // Theme
  root.setAttribute("data-theme", settings.theme);

  // Auto: respect system preference
  if (settings.theme === "auto") {{
    const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
    root.setAttribute("data-theme", prefersDark ? "dark" : "light");
  }}

  // Density
  root.setAttribute("data-density", settings.density);

  // Accent color
  root.style.setProperty("--dg-accent", settings.accent);

  // Avatar set
  if (settings.avatarSet) {{
    root.setAttribute("data-avatar-set", settings.avatarSet);
  }}

  // Reduced-motion detection
  const prefersReducedMotion = window.matchMedia(
    "(prefers-reduced-motion: reduce)"
  ).matches;

  // Effects
  config.effects.forEach((effectDef) => {{
    const wanted = settings.effects[effectDef.id] ?? false;
    const allowed =
      !prefersReducedMotion ||
      effectDef.reduced_motion_behavior !== "disable";
    const active = wanted && allowed;
    root.setAttribute(
      `data-effect-${{effectDef.id}}`,
      active ? "on" : "off"
    );
  }});
}}
'''

# ---------------------------------------------------------------------------
# Vue templates
# ---------------------------------------------------------------------------

_VUE_DESIGN_SETTINGS_VUE = '''\
<!-- DesignSettings.vue -- PROPOSAL (see WIRING.md before integrating) -->
<!-- Generated by design_tab_scaffold.py -- ASCII-only output. -->

<template>
  <div class="design-settings" :data-density="density">
    <h2>Design Settings</h2>

    <section>
      <label>Theme</label>
      <select v-model="theme" @change="apply">
        <option v-for="m in config.theme.modes" :key="m" :value="m">{{ m }}</option>
      </select>
    </section>

    <section>
      <label>Density</label>
      <select v-model="density" @change="apply">
        <option v-for="d in config.density.options" :key="d" :value="d">{{ d }}</option>
      </select>
    </section>

    <section>
      <label>Accent color</label>
      <div style="display:flex;gap:8px;">
        <button
          v-for="color in config.accent.options"
          :key="color"
          :style="{
            background: color,
            width: \'32px\',
            height: \'32px\',
            border: accent === color ? \'3px solid #000\' : \'2px solid #ccc\',
            borderRadius: \'4px\',
            cursor: \'pointer\'
          }"
          :aria-label="\'Select accent \' + color"
          @click="accent = color; apply()"
        />
      </div>
    </section>

    <section v-if="config.avatars.enabled">
      <label>Avatar style</label>
      <select v-model="avatarSet" @change="apply">
        <option v-for="s in config.avatars.sets" :key="s" :value="s">{{ s }}</option>
      </select>
    </section>

    <section v-if="config.effects.length > 0">
      <label>Effects</label>
      <label
        v-for="effect in config.effects"
        :key="effect.id"
        style="display:flex;align-items:center;gap:8px;"
      >
        <input
          type="checkbox"
          :checked="effects[effect.id] ?? effect.enabled"
          @change="toggleEffect(effect.id, $event)"
        />
        {{ effect.label }}
        <span v-if="effect.fallback">(fallback: {{ effect.fallback }})</span>
      </label>
    </section>
  </div>
</template>

<script setup>
import {{ ref, reactive }} from "vue";
import {{ applyDesignConfig }} from "./applyDesignConfig.js";

const props = defineProps(["config"]);
const config = props.config;

const theme = ref(config.theme.default);
const density = ref(config.density.default);
const accent = ref(config.accent.default);
const avatarSet = ref(config.avatars.enabled ? config.avatars.default : "");
const effects = reactive(
  Object.fromEntries(config.effects.map((e) => [e.id, e.enabled]))
);

function toggleEffect(id, event) {{
  effects[id] = event.target.checked;
  apply();
}}

function apply() {{
  applyDesignConfig(
    {{ theme: theme.value, density: density.value, accent: accent.value,
       avatarSet: avatarSet.value, effects: {{ ...effects }} }},
    config
  );
}}
</script>
'''

_VUE_APPLY_CONFIG_JS = '''\
// applyDesignConfig.js -- PROPOSAL (see WIRING.md before integrating)
// Generated by design_tab_scaffold.py -- ASCII-only output.

export function applyDesignConfig(settings, config) {
  const root = document.documentElement;

  root.setAttribute("data-theme", settings.theme);

  if (settings.theme === "auto") {
    const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
    root.setAttribute("data-theme", prefersDark ? "dark" : "light");
  }

  root.setAttribute("data-density", settings.density);
  root.style.setProperty("--dg-accent", settings.accent);

  if (settings.avatarSet) {
    root.setAttribute("data-avatar-set", settings.avatarSet);
  }

  const prefersReducedMotion = window.matchMedia(
    "(prefers-reduced-motion: reduce)"
  ).matches;

  (config.effects || []).forEach(function(effectDef) {
    const wanted = settings.effects[effectDef.id] ?? false;
    const allowed =
      !prefersReducedMotion ||
      effectDef.reduced_motion_behavior !== "disable";
    const active = wanted && allowed;
    root.setAttribute(
      "data-effect-" + effectDef.id,
      active ? "on" : "off"
    );
  });
}
'''

# ---------------------------------------------------------------------------
# Plain HTML/JS templates
# ---------------------------------------------------------------------------

_PLAIN_DESIGN_SETTINGS_HTML = '''\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Design Settings -- Proposal</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 480px; margin: 2em auto;
         padding: 0 1em; }}
  section {{ margin: 1.2em 0; }}
  label {{ display: block; font-weight: bold; margin-bottom: 4px; }}
  select {{ width: 100%; padding: 6px; border: 1px solid #ccc; border-radius: 4px; }}
  .accent-btn {{ width: 32px; height: 32px; border: 2px solid #ccc;
                 border-radius: 4px; cursor: pointer; margin: 2px; }}
  .accent-btn.selected {{ border: 3px solid #000; }}
  .effect-row {{ display: flex; align-items: center; gap: 8px; margin: 4px 0; }}
  h1 {{ font-size: 1.4em; }}
</style>
</head>
<body>
<h1>Design Settings <small style="font-size:0.6em;font-weight:normal;">(Proposal)</small></h1>
<div id="settings-root"></div>
<script type="module">
import {{ applyDesignConfig }} from "./design-settings.js";

// Config is embedded at scaffold time; replace with fetch("/design-config.json") in production.
const CONFIG_PLACEHOLDER = "__DESIGN_CONFIG_JSON__";

const state = {{
  theme: CONFIG_PLACEHOLDER.theme.default,
  density: CONFIG_PLACEHOLDER.density.default,
  accent: CONFIG_PLACEHOLDER.accent.default,
  avatarSet: CONFIG_PLACEHOLDER.avatars.enabled ? CONFIG_PLACEHOLDER.avatars.default : "",
  effects: Object.fromEntries(CONFIG_PLACEHOLDER.effects.map(e => [e.id, e.enabled])),
}};

function apply() {{
  applyDesignConfig(state, CONFIG_PLACEHOLDER);
}}

function render() {{
  const root = document.getElementById("settings-root");
  root.innerHTML = buildHTML();
  bindEvents();
  apply();
}}

function buildHTML() {{
  const cfg = CONFIG_PLACEHOLDER;
  let html = "";

  // Theme
  html += `<section><label for="sel-theme">Theme</label>
    <select id="sel-theme">
      ${{cfg.theme.modes.map(m => `<option value="${{m}}" ${{state.theme===m?"selected":""}}>
        ${{m}}</option>`).join("")}}
    </select></section>`;

  // Density
  html += `<section><label for="sel-density">Density</label>
    <select id="sel-density">
      ${{cfg.density.options.map(d => `<option value="${{d}}" ${{state.density===d?"selected":""}}>
        ${{d}}</option>`).join("")}}
    </select></section>`;

  // Accent
  html += `<section><label>Accent color</label><div id="accent-btns">
    ${{cfg.accent.options.map(c => `<button class="accent-btn${{state.accent===c?" selected":""}}"
        style="background:${{c}};" data-color="${{c}}" aria-label="Select accent ${{c}}"></button>`)
        .join("")}}
    </div></section>`;

  // Avatars
  if (cfg.avatars.enabled) {{
    html += `<section><label for="sel-avatar">Avatar style</label>
      <select id="sel-avatar">
        ${{cfg.avatars.sets.map(s => `<option value="${{s}}" ${{state.avatarSet===s?"selected":""}}>
          ${{s}}</option>`).join("")}}
      </select></section>`;
  }}

  // Effects
  if (cfg.effects.length > 0) {{
    html += `<section><label>Effects</label>
      ${{cfg.effects.map(e => `<div class="effect-row">
        <input type="checkbox" id="eff-${{e.id}}" ${{(state.effects[e.id]??e.enabled)?"checked":""}}>
        <label for="eff-${{e.id}}">${{e.label}}</label>
        ${{e.fallback ? `<small>(fallback: ${{e.fallback}})</small>` : ""}}
        </div>`).join("")}}
      </section>`;
  }}

  return html;
}}

function bindEvents() {{
  const cfg = CONFIG_PLACEHOLDER;

  const themeEl = document.getElementById("sel-theme");
  if (themeEl) themeEl.addEventListener("change", e => {{ state.theme = e.target.value; apply(); }});

  const densityEl = document.getElementById("sel-density");
  if (densityEl) densityEl.addEventListener("change", e => {{ state.density = e.target.value; apply(); }});

  document.querySelectorAll(".accent-btn").forEach(btn => {{
    btn.addEventListener("click", () => {{
      state.accent = btn.dataset.color;
      document.querySelectorAll(".accent-btn").forEach(b => b.classList.remove("selected"));
      btn.classList.add("selected");
      apply();
    }});
  }});

  const avatarEl = document.getElementById("sel-avatar");
  if (avatarEl) avatarEl.addEventListener("change", e => {{ state.avatarSet = e.target.value; apply(); }});

  cfg.effects.forEach(eff => {{
    const el = document.getElementById("eff-" + eff.id);
    if (el) el.addEventListener("change", e => {{
      state.effects[eff.id] = e.target.checked;
      apply();
    }});
  }});
}}

render();
</script>
</body>
</html>
'''

_PLAIN_DESIGN_SETTINGS_JS = '''\
// design-settings.js -- PROPOSAL (see WIRING.md before integrating)
// Generated by design_tab_scaffold.py -- ASCII-only output.

export function applyDesignConfig(settings, config) {
  const root = document.documentElement;

  root.setAttribute("data-theme", settings.theme);

  if (settings.theme === "auto") {
    const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
    root.setAttribute("data-theme", prefersDark ? "dark" : "light");
  }

  root.setAttribute("data-density", settings.density);
  root.style.setProperty("--dg-accent", settings.accent);

  if (settings.avatarSet) {
    root.setAttribute("data-avatar-set", settings.avatarSet);
  }

  const prefersReducedMotion = window.matchMedia(
    "(prefers-reduced-motion: reduce)"
  ).matches;

  (config.effects || []).forEach(function(effectDef) {
    const wanted = !!(settings.effects[effectDef.id]);
    const allowed =
      !prefersReducedMotion ||
      effectDef.reduced_motion_behavior !== "disable";
    const active = wanted && allowed;
    root.setAttribute(
      "data-effect-" + effectDef.id,
      active ? "on" : "off"
    );
  });
}
'''

_WIRING_MD_TEMPLATE = '''\
# Design Tab -- Wiring Guide (PROPOSAL)

Generated by design_tab_scaffold.py for framework: {framework}

## IMPORTANT

This is a PROPOSAL. These files belong in:
    docs/design/proposals/design-tab/

Do NOT copy DesignSettings.{ext} or applyDesignConfig.{apply_ext} into src/ directly.
Integration happens via /qGoal after design review and user sign-off.

## What was generated

{files_list}

## Where to place files (when implementing)

- DesignSettings component -> src/components/settings/ (or equivalent)
- applyDesignConfig helper -> src/utils/ or src/lib/
- design-config.json -> src/assets/ or public/ (static, loaded at runtime)

## How it works

1. Mount <DesignSettings config={{config}} /> (or equivalent) in your settings page/modal.
2. On any user change, the component calls applyDesignConfig(settings, config).
3. applyDesignConfig sets on document.documentElement:
   - data-theme attribute (light | dark | auto-resolved)
   - data-density attribute (compact | regular | roomy)
   - --dg-accent CSS custom property (hex color)
   - data-avatar-set attribute (if avatars enabled)
   - data-effect-<id> attribute per effect (on | off)
4. Your CSS then reads these attributes:
   [data-theme="dark"] {{ ... }}
   [data-density="compact"] {{ --space-unit: 4px; ... }}
   :root {{ --dg-accent: #2fa36b; /* default overridden at runtime */ }}
5. Reduced motion: effects with reduced_motion_behavior="disable" are automatically
   forced off when the OS prefers-reduced-motion media query is active.

## design-config.json location

Ship the config from a path your app can fetch:
    GET /design-config.json

Or import it statically in the component. The scaffold copies the config alongside
the component files as a reference.

## Next step

When ready to implement, run:
    /qGoal implement docs/design/proposals/design-tab/ --check antipattern_lint_clean
'''


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def _safe_ascii(s):
    return str(s).encode('ascii', errors='replace').decode('ascii')


def _read_config(config_path):
    try:
        with open(config_path, 'r', encoding='utf-8', errors='replace') as fh:
            return json.load(fh)
    except Exception:
        return {}


def _write_file(path, content):
    """Write content to path, creating parent dirs. Content must be str."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as fh:
        fh.write(content)


def _inject_config(template, config):
    """Embed JSON config into the plain HTML template's placeholder."""
    config_json = json.dumps(config, ensure_ascii=True, indent=2)
    return template.replace('"__DESIGN_CONFIG_JSON__"', config_json)


def main():
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument('--framework', default=None)
    parser.add_argument('--config', default=None)
    parser.add_argument('--out', default=None)

    try:
        args, _unknown = parser.parse_known_args()
    except Exception:
        print(json.dumps({"error": "bad arguments"}))
        return

    framework = (args.framework or '').lower().strip()
    config_path = args.config
    out_dir_arg = args.out

    if framework not in ('react', 'vue', 'plain'):
        print(json.dumps({"error": "framework must be react, vue, or plain"}))
        return

    if not config_path:
        print(json.dumps({"error": "--config path required"}))
        return

    config = _read_config(config_path)
    if not config:
        # Emit empty config as fallback
        config = {"version": 1, "theme": {"modes": ["light", "dark", "auto"], "default": "auto"},
                  "density": {"options": ["compact", "regular", "roomy"], "default": "regular"},
                  "accent": {"options": [], "default": ""},
                  "avatars": {"sets": [], "default": "", "enabled": False},
                  "effects": []}

    # Determine output directory
    if out_dir_arg:
        out_dir = os.path.abspath(out_dir_arg)
    else:
        out_dir = os.path.abspath(os.path.join('docs', 'design', 'proposals', 'design-tab'))

    written_files = []

    try:
        if framework == 'react':
            files = {
                'DesignSettings.tsx': _REACT_DESIGN_SETTINGS_TSX,
                'applyDesignConfig.ts': _REACT_APPLY_CONFIG_TS,
                'design-config.json': json.dumps(config, ensure_ascii=True, indent=2),
            }
            ext = 'tsx'
            apply_ext = 'ts'
        elif framework == 'vue':
            files = {
                'DesignSettings.vue': _VUE_DESIGN_SETTINGS_VUE,
                'applyDesignConfig.js': _VUE_APPLY_CONFIG_JS,
                'design-config.json': json.dumps(config, ensure_ascii=True, indent=2),
            }
            ext = 'vue'
            apply_ext = 'js'
        else:  # plain
            html_content = _inject_config(_PLAIN_DESIGN_SETTINGS_HTML, config)
            files = {
                'design-settings.html': html_content,
                'design-settings.js': _PLAIN_DESIGN_SETTINGS_JS,
                'design-config.json': json.dumps(config, ensure_ascii=True, indent=2),
            }
            ext = 'html'
            apply_ext = 'js'

        files_list_md = "\n".join("- " + f for f in sorted(files.keys()))
        wiring = _WIRING_MD_TEMPLATE.format(
            framework=framework,
            ext=ext,
            apply_ext=apply_ext,
            files_list=files_list_md,
        )
        files['WIRING.md'] = wiring

        for fname, content in files.items():
            out_path = os.path.join(out_dir, fname)
            # Safety: ensure we never write outside out_dir
            out_path_abs = os.path.abspath(out_path)
            out_dir_abs = os.path.abspath(out_dir)
            if not out_path_abs.startswith(out_dir_abs + os.sep) and out_path_abs != out_dir_abs:
                continue  # skip silently (should not happen with simple filenames)
            _write_file(out_path, content)
            written_files.append(fname)

    except Exception as exc:
        print(json.dumps({"error": "write failed: " + str(exc)}))
        return

    result = {
        "out": out_dir,
        "framework": framework,
        "files": sorted(written_files),
    }
    print(json.dumps(result, ensure_ascii=True))


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(json.dumps({"error": str(exc)}))
        sys.exit(0)
